// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AmplfiyNode$AwsSdkReClientAmplifyNode = require("../src/AmplfiyNode.bs.js");

AmplfiyNode$AwsSdkReClientAmplifyNode.send(AmplfiyNode$AwsSdkReClientAmplifyNode.createCommand);

/*  Not a pure module */
